### PR TITLE
Merge the manifest changes

### PR DESCRIPTION
**Pull request by fallenbagel**
Merge the manifest changes so I could start hosting it for easier installation for `v2.0.0`

### CODE REVIEW

**Comment by Fallenbagel** [comment]
@themegaphoenix I hope that's okay with you that I opened this PR?

**Comment by themegaphoenix** [comment]
> @themegaphoenix I hope that's okay with you that I opened this PR?

Oh yes I forgot to open a PR. I was testing it for a while then just forgot about it.

**Comment by Fallenbagel** [comment]
> Oh yes I forgot to open a PR. I was testing it for a while then just forgot about it.

Does it work? Any issues w it? I'm kinda very new to hosting plugins and since I've found a bunch of people already do use this plugin, I thought to ease their pain of installing

**Comment by themegaphoenix** [comment]
> > Oh yes I forgot to open a PR. I was testing it for a while then just forgot about it.
> 
> Does it work? Any issues w it? I'm kinda very new to hosting plugins and since I've found out that a bunch of people already use this plugin, I thought to ease their pain of installing

No issues with the way it works.
The only problem is the season detection, but that was already present in the original version.

A few minutes ago I found a new plugin that aims to fix the season detection, but it depends on manual mapping:
https://github.com/vosmiic/jellyfin-ani-sync

**Comment by Fallenbagel** [comment]
> > > Oh yes I forgot to open a PR. I was testing it for a while then just forgot about it.
> > 
> > 
> > Does it work? Any issues w it? I'm kinda very new to hosting plugins and since I've found out that a bunch of people already use this plugin, I thought to ease their pain of installing
> 
> No issues with the way it works. The only problem is the season detection, but that was already present in the original version.
> 
> A few minutes ago I found a new plugin that aims to fix the season detection, but it depends on manual mapping: https://github.com/vosmiic/jellyfin-ani-sync

Which season detection? I have it working perfectly as my library is set as TMDB as primary and anilist as secondary. Never had any issues

**Comment by themegaphoenix** [comment]
> > > > Oh yes I forgot to open a PR. I was testing it for a while then just forgot about it.
> > > 
> > > 
> > > Does it work? Any issues w it? I'm kinda very new to hosting plugins and since I've found out that a bunch of people already use this plugin, I thought to ease their pain of installing
> > 
> > 
> > No issues with the way it works. The only problem is the season detection, but that was already present in the original version.
> > A few minutes ago I found a new plugin that aims to fix the season detection, but it depends on manual mapping: https://github.com/vosmiic/jellyfin-ani-sync
> 
> @themegaphoenix Season detection? I have never had that issue. I have it working perfectly with my library set as TMDB as primary and anilist as secondary. Never had any issues

See here this comment:
https://www.reddit.com/r/jellyfin/comments/phyl98/comment/hz60v1b/?utm_source=share&utm_medium=web2x&context=3

**Comment by fallenbagel** [comment]
> See here this comment:
> https://www.reddit.com/r/jellyfin/comments/phyl98/comment/hz60v1b/?utm_source=share&utm_medium=web2x&context=3

Hmm 🤔
I think I know why. In Anilist, they consider each season as its own seperate anime than same

**Pull request merged**
